theme: minima 
title: Sam's Land
author: Samuel McGinnis
description: Give me money, nvm, this is a school assignment... Hello this is an update through this description explaining who I am and what I like to do. First off, I like gaming such as Roblox, Minecraft, and Steam games. Then I like to eat spicy things; currently, I am growing habanero peppers. 
